### ISSUE TITLE
improve loggin

### ISSUE THREAD

**Issue by LeanderK** [intellimate/Izou#17]
The current state of debugging is not optimal.
Debug messages should be printed to the log, otherwise it is very hard to track what caused an error.
There is no indication which about the state of Izou. Important Logic doesn't print their status.

The goal of this proposal is:
- log important events
- log stages
- write debug to the log-File

**Comment by jundl77** [comment]
debug is already in the log files for the addOn's I did this a couple days ago, and yes we need to talk about that in person I found a couple uncommented bug sources already

**Comment by LeanderK** [comment]
This proposal is not about eliminating bugs, but rather about creating tools for testing

**Comment by LeanderK** [comment]
ok,
maybe we can collect them and tackle when we implement this proposal
