### ISSUE TITLE
Security-related bugs

### ISSUE THREAD

**Issue by LeanderK** [intellimate/Izou#33]
i'll just post every bug (at least what i think is a bug) i encounter in this thread

**Comment by LeanderK** [comment]
ok, i am waiting for rultor right now (useless with old sdk).
@jundl77 you have to write the cause of the security exceptions in the log-files. The console output becomes unreadable because in a multithreaded environment everyone writes parallel into the console output. Longer outputs (which are, btw, not really good if you are not developing this thing right now) become unreadable. (example: http://pastebin.com/ynu5YGhY)

**Comment by LeanderK** [comment]
http://pastebin.com/7stMNbMb number 1 ;)

**Comment by LeanderK** [comment]
http://pastebin.com/XChXDidp number 2, first one was without configured properties files

**Comment by LeanderK** [comment]
ok, i forgot to add rplay = airplay, i forgot to add the socket permissions

**Comment by LeanderK** [comment]
izouIRMovement uses pf4j (therefore izou has to run in sudo mode)

**Comment by jundl77** [comment]
I cannot make the console output shorter, because the mail addOn is just writing all that (It is printing the attachement (in this case the log file))

**Comment by jundl77** [comment]
Hmm and can you not run just the IR movement with sudo? I mean running the whole thing in sudo seems a bit unsafe

**Comment by LeanderK** [comment]
no, that is not possible...no IO without sudo

**Comment by LeanderK** [comment]
there is a mail add-on?

**Comment by LeanderK** [comment]
btw whats the purpose of allowedSocketConnections?

**Comment by LeanderK** [comment]
also, with IO things pf4j has to do some bridging to native code (drivers) outside izou to work.

**Comment by LeanderK** [comment]
FileSystem.FULL_WORKING_DIRECTORY is not available anymore

**Comment by LeanderK** [comment]
LOG_PATH etc. also
